version: '3'

services:

  postgres:
    image: postgres:14.8-alpine
    env_file:
      - ./.env
    ports:
      - 5432:5432
    volumes:
      - ./datadir:/var/lib/postgresql/data

  nextapp:
    image: nextapp:1.0.0
    env_file:
      - ./.env
    ports:
      - 3000:3000
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: 2G
        reservations:
          cpus: '1'
          memory: 2G

  flaskapp:
    image: flaskapp:1.0.0
    env_file:
      - ./.env
    ports:
      - 5000:5000
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: 2G
        reservations:
          cpus: '1'
          memory: 2G
